'use client';
import {useEffect,useState} from 'react';
import type {Account,Profile} from '@/lib/account';
export default function ProfileScreen({account,onClose}:{account:Account;onClose:()=>void}){
 const [name,setName]=useState(''),[handle,setHandle]=useState(''),[avatar,setAvatar]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/profile',{cache:'no-store'});const d=await r.json() as {error?:string;profile:Profile|null;url:string};if(!r.ok)throw Error(d.error||'Please try again.');setName(d.profile?.display_name||'');setHandle(d.profile?.username||'');setAvatar(d.profile?.avatar_url||'')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 return <><button className="tl-link" onClick={onClose}>Back to closet</button><h1>Your account</h1>{loading?<p role="status">Loading your profile…</p>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({display_name:name,username:handle,avatar_url:avatar})});const d=await r.json() as {error?:string;profile:Profile|null;url:string};if(!r.ok)throw Error(d.error||'Please try again.');setName(d.profile!.display_name);setHandle(d.profile!.username||'');setNotice('Profile saved.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>
 <fieldset disabled={busy} className="tl-profile-fields"><div className="tl-profile-photo">{avatar?<img src={avatar} alt="Your profile photo"/>:<span aria-label="Default avatar">{name.trim().slice(0,1).toUpperCase()||'T'}</span>}</div>
 <label className="tl-field"><span>Profile photo <small>(optional)</small></span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setError('');setNotice('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){setError('Choose a JPEG, PNG, or WebP photo under 5 MB.');return}setBusy(true);try{const form=new FormData();form.append('file',file);const r=await fetch('/api/media',{method:'POST',body:form});const d=await r.json() as {error?:string;profile:Profile|null;url:string};if(!r.ok)throw Error(d.error||'Please try again.');setAvatar(d.url);setNotice('Photo ready. Save your profile to keep it.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}/></label>{avatar&&<button type="button" className="tl-link" onClick={()=>{setAvatar('');setNotice('Save your profile to remove the photo.')}}>Remove photo</button>}
 <label className="tl-field"><span>Display name</span><input required maxLength={80} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label><label className="tl-field"><span>Username / handle</span><input maxLength={30} minLength={3} pattern="[A-Za-z0-9_]{3,30}" autoCapitalize="none" autoComplete="username" spellCheck={false} value={handle} onChange={e=>setHandle(e.target.value)}/><small>Optional. 3–30 letters, numbers, or underscores.</small></label><label className="tl-field"><span>Email</span><input type="email" readOnly value={account.email}/><small>Your sign-in email.</small></label><button className="tl-button" disabled={busy}>{busy?'Saving…':'Save profile'}</button></fieldset></form>}{error&&<div role="alert"><p className="tl-error">{error}</p><button className="tl-link" disabled={busy} onClick={load}>Reload profile</button></div>}{notice&&<p role="status">{notice}</p>}</>
}
