'use client';
import {useEffect,useRef,useState} from 'react';
import {X,ChevronLeft,Check,Sparkles,LoaderCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {blankGarment,primaryPhoto,type GarmentMetadata,type ClosetItem} from '@/lib/closet';
import {applySuggestions,paletteSuggestions,type GarmentSuggestion} from '@/lib/garment-suggestions';
import {PhotoPicker,requestId} from './photo-picker';
import {CategoryChoices} from './metadata-fields';
import {MetadataFields} from './metadata-fields';
export async function closetRequest(body:unknown){const r=await fetch('/api/closet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json().catch(()=>({error:'Could not save right now. Your changes are still here.'}));if(!r.ok)throw Error(d.error||'Unable to save. Please try again.');return d}
async function samplePhoto(url:string){const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=100;canvas.height=Math.max(1,Math.round(100*img.naturalHeight/img.naturalWidth));const ctx=canvas.getContext('2d');if(!ctx)return [];ctx.drawImage(img,0,0,canvas.width,canvas.height);return paletteSuggestions(ctx.getImageData(0,0,canvas.width,canvas.height).data,canvas.width,canvas.height)}
export function GarmentForm({item,mode='details',onClose,onSaved}:{item?:ClosetItem;mode?:'details'|'photos';onClose:()=>void;onSaved:(data:any,id:string)=>void}){
 const [draft,setDraft]=useState<GarmentMetadata>(item||blankGarment()),[step,setStep]=useState(item?(mode==='photos'?'photos':'details'):'photos'),[id]=useState(requestId),[uploading,setUploading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[suggestions,setSuggestions]=useState<GarmentSuggestion[]>([]),[selected,setSelected]=useState<string[]>([]),[analyzing,setAnalyzing]=useState(false),[analysisNote,setAnalysisNote]=useState(''),[discard,setDiscard]=useState(false),[changed,setChanged]=useState(false);const analysisGeneration=useRef(0),initial=useRef(JSON.stringify(item||blankGarment()));const body=useRef<HTMLDivElement>(null);
 useEffect(()=>{body.current?.scrollTo(0,0)},[step]);useEffect(()=>()=>{analysisGeneration.current++},[]);
 function update(next:GarmentMetadata){setDraft(next);setChanged(JSON.stringify(next)!==initial.current)}
 function close(){if(uploading||saving)return;if(changed)setDiscard(true);else onClose()}
 async function analyze(category:string){const next={...draft,category};update(next);setStep('review');setAnalyzing(true);setSuggestions([]);setSelected([]);setAnalysisNote('');const generation=++analysisGeneration.current;try{const result=await samplePhoto(primaryPhoto(next));if(generation!==analysisGeneration.current)return;setSuggestions(result);setAnalysisNote(result.length?'These are colors sampled from your photo. Lighting and the background can affect them. Brand, material and garment recognition are not connected yet.':'No reliable color suggestions from this photo. You can save now and add details later.')}catch{if(generation===analysisGeneration.current)setAnalysisNote('This photo could not be analyzed. You can still save your garment.')}finally{if(generation===analysisGeneration.current)setAnalyzing(false)}}
 async function save(){if(saving||uploading)return;setSaving(true);setError('');try{const d=await closetRequest({action:'save',item:draft,id:item?.id,requestId:id});onSaved(d,d.id);onClose()}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 function accept(){update(applySuggestions(draft,suggestions,selected));setSuggestions([]);setSelected([]);setAnalysisNote('Selected suggestions added. You can change them in Details.');}
 const title=item?(step==='photos'?'Your photos':'Edit garment'):step==='photos'?'Add a garment':step==='category'?'What kind of garment?':step==='details'?'Make it yours':'Ready for your closet';
 return <Dialog open onOpenChange={v=>!v&&close()}><DialogContent className="tl-dialog tl-flow" showCloseButton={false}><div className="tl-flow-head"><button className="tl-icon" type="button" aria-label={step==='photos'||item?'Close':'Back'} disabled={saving||uploading} onClick={()=>{if(item||step==='photos')close();else if(step==='details')setStep('review');else {analysisGeneration.current++;setAnalyzing(false);setStep(step==='review'?'category':'photos')}}}>{item||step==='photos'?<X size={22}/>:<ChevronLeft size={24}/>}</button><div><DialogTitle>{title}</DialogTitle><DialogDescription>{item?'Changes stay with this garment.':step==='photos'?'One garment, as many angles as you need.':step==='category'?'Just a category. Everything else is optional.':step==='details'?'Add as much or as little as you like.':'Save now. Add the story whenever you like.'}</DialogDescription></div>{!item&&<span className="tl-step">{step==='photos'?'1':step==='category'?'2':'3'} / 3</span>}</div>
 <div className="tl-flow-body" ref={body}>
 {step==='photos'&&<PhotoPicker draft={draft} onChange={update} onBusy={setUploading}/>}
 {step==='category'&&<><img className="tl-category-photo" src={primaryPhoto(draft)} alt="Your garment"/><CategoryChoices value={draft.category} onChange={value=>update({...draft,category:value})} onSelect={analyze}/></>}
 {step==='review'&&<><div className="tl-review-hero"><img src={primaryPhoto(draft)} alt="Your garment"/><div><span className="tl-kicker">{draft.category}</span><h3>{draft.name||draft.subcategory||'Your next favorite.'}</h3><button className="tl-link" type="button" onClick={()=>setStep('photos')}>Change photos</button></div></div><section className="tl-suggestions"><div className="tl-section-line"><h3><Sparkles size={18}/> Photo suggestions</h3><span>Optional</span></div>{analyzing?<p role="status" className="tl-analysis"><LoaderCircle className="tl-spin" size={18}/> Looking at the photo… You can save now.</p>:<><p className="tl-hint">{analysisNote}</p>{suggestions.length>0&&<><p className="tl-hint">Tap the colors you want to keep. Nothing is selected automatically.</p><div className="tl-chip-wrap">{suggestions.map(s=><button type="button" key={s.id} aria-pressed={selected.includes(s.id)} onClick={()=>setSelected(v=>v.includes(s.id)?v.filter(i=>i!==s.id):[...v,s.id])}>{s.value}{selected.includes(s.id)&&<Check size={15}/>}</button>)}</div><button className="tl-button secondary" type="button" disabled={!selected.length} onClick={accept}>Use selected suggestions</button></>}{draft.colors.length>0&&<p className="tl-confirmed"><Check size={15}/> Colors: {draft.colors.join(', ')}</p>}</>}</section><button className="tl-detail-link" type="button" onClick={()=>setStep('details')}><span><strong>Add optional details</strong><small>Name, brand, size, price and more</small></span><PlusIcon/></button></>}
 {step==='details'&&<MetadataFields draft={draft} onChange={update} showCategory={!!item}/>}
 {error&&<p role="alert" className="tl-error">{error}</p>}
 </div><div className="tl-flow-footer">{step==='photos'&&!item?<button className="tl-button" disabled={!draft.photos.length||uploading} onClick={()=>setStep('category')}>{uploading?'Adding photo…':'Choose category'}</button>:step==='category'?<button className="tl-button" disabled={!draft.category||uploading} onClick={()=>analyze(draft.category)}>Continue</button>:<button className="tl-button" disabled={saving||uploading||!draft.photos.length||!draft.category} onClick={save}>{saving?'Saving…':item?'Save changes':'Save to closet'}</button>}{step==='details'&&!item&&<button className="tl-link" onClick={()=>setStep('review')}>Back to review</button>}</div>
 {discard&&<div className="tl-discard" role="alertdialog" aria-label="Discard unsaved changes"><h3>Keep working on this garment?</h3><p>Your changes have not been saved.</p><button className="tl-button" onClick={()=>setDiscard(false)}>Keep editing</button><button className="tl-link" onClick={onClose}>Discard changes</button></div>}
 </DialogContent></Dialog>
}
function PlusIcon(){return <span aria-hidden="true" className="tl-plus">+</span>}
