'use client';
import {useRef,useState} from 'react';
import {Camera,Images,Check,Plus,Trash2} from 'lucide-react';
import {garmentPhotos,withPhotos,type GarmentMetadata,type GarmentPhoto} from '@/lib/closet';
export function requestId(){return Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('')}
async function decodePhoto(file:File):Promise<{source:CanvasImageSource;width:number;height:number;close:()=>void}>{try{const bitmap=await createImageBitmap(file);return {source:bitmap,width:bitmap.width,height:bitmap.height,close:()=>bitmap.close()}}catch{const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();return {source:img,width:img.naturalWidth,height:img.naturalHeight,close:()=>URL.revokeObjectURL(url)}}catch{URL.revokeObjectURL(url);throw Error('This photo could not be opened. Try another photo or take a new one.')}}}
async function preparePhoto(file:File){if(file.size>25*1024*1024)throw Error('This photo is too large. Try a smaller copy.');const image=await decodePhoto(file);try{const scale=Math.min(1,1600/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw Error('Unable to prepare this photo.');ctx.fillStyle='#f4f3ef';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image.source,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/jpeg',.83));if(!blob)throw Error('Unable to prepare this photo.');return new File([blob],'garment.jpg',{type:'image/jpeg'})}finally{image.close()}}
export function PhotoPicker({draft,onChange,onBusy}:{draft:GarmentMetadata;onChange:(d:GarmentMetadata)=>void;onBusy:(b:boolean)=>void}){
 const camera=useRef<HTMLInputElement>(null),library=useRef<HTMLInputElement>(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState('');const assets=garmentPhotos(draft);
 async function choose(files:FileList|null){if(!files?.length)return;const list=Array.from(files);setError('');if(assets.length+list.length>8){setError('Keep up to 8 photos of this garment. Remove one to make room.');return}setBusy(true);onBusy(true);let updated=draft;try{for(let i=0;i<list.length;i++){setProgress(`Adding photo ${i+1} of ${list.length}…`);const file=await preparePhoto(list[i]);const local=URL.createObjectURL(file);setPreview(local);try{const f=new FormData();f.set('file',file);const r=await fetch('/api/media',{method:'POST',body:f});const result:any=await r.json().catch(()=>({error:'Your photo could not be saved. Please try again.'}));if(!r.ok)throw Error(result.error||'Your photo could not be saved.');const photo:GarmentPhoto={id:requestId(),url:result.url,kind:'garment'};updated=withPhotos(updated,[...garmentPhotos(updated),photo],updated.primaryPhotoId);onChange(updated)}finally{URL.revokeObjectURL(local);setPreview('')}}}catch(e){setError((e as Error).message)}finally{setBusy(false);onBusy(false);setProgress('')}}
 return <div className="tl-photo-picker"><input ref={camera} hidden type="file" accept="image/*" capture="environment" aria-label="Take a photo" onChange={e=>{choose(e.target.files);e.target.value=''}}/><input ref={library} hidden type="file" accept="image/*" multiple aria-label="Choose photos" onChange={e=>{choose(e.target.files);e.target.value=''}}/>{!assets.length&&!preview?<div className="tl-photo-empty"><Camera size={44} strokeWidth={1}/><h3>Start with your garment.</h3><p>A quick photo is all it takes.<br/>You can add labels and details later.</p></div>:<div className="tl-photo-grid">{assets.map((p,i)=><div className="tl-photo-tile" key={p.id}><img src={p.url} alt={`Garment photo ${i+1}`}/><div className="tl-photo-controls"><button type="button" disabled={busy} className={p.id===draft.primaryPhotoId?'is-primary':''} aria-pressed={p.id===draft.primaryPhotoId} onClick={()=>onChange(withPhotos(draft,assets,p.id))}>{p.id===draft.primaryPhotoId?<><Check size={14}/> Primary</>:'Make primary'}</button><button type="button" disabled={busy} aria-label={`Remove photo ${i+1}`} onClick={()=>onChange(withPhotos(draft,assets.filter(a=>a.id!==p.id),draft.primaryPhotoId))}><Trash2 size={17}/></button></div></div>)}{preview&&<div className="tl-photo-tile tl-photo-pending"><img src={preview} alt="New photo preview"/><span>Saving photo…</span></div>}</div>}
 {assets.length<8&&<div className="tl-photo-actions"><button type="button" className="tl-button" disabled={busy} onClick={()=>camera.current?.click()}><Camera size={19}/> Take photo</button><button type="button" className="tl-button secondary" disabled={busy} onClick={()=>library.current?.click()}><Images size={19}/> Choose from photos</button></div>}{!!assets.length&&<p className="tl-hint">{assets.length} of 8 photos · The primary photo appears in your closet.</p>}{busy&&<p role="status" className="tl-hint">{progress}</p>}{error&&<p role="alert" className="tl-error">{error}</p>}</div>
}
